### ISSUE TITLE
Struct.Error

### ISSUE THREAD

**Issue by teetz** [mpapi/lazylights#6]
So whenever I try to run lazylights.find_bulbs(expected_bulbs = 1) I get the error: traceback (most recent call last): file"<stdin>", line 1, in <module>
file "C:\Program Files (x86)\Python 3.5\Lib\site-packages\lazylights.py", line 23, in find_bulbs protocol=PROTOCOL_DISCOVERY) file "C:\Program Files (x86)\Python 3.5\Lib\site-packages\lazylights.py", line98, in build_packet *payload_args) struct.error: argument for "s" must be a bytes object

I tried to go to the file listed in the file path, but it doesn't appear there and I've tried hiding and unhiding files. Any ideas?

**Comment by mpapi** [comment]
Hi @teetz, are you using Python 3? I'm pretty sure that's your issue -- I've been (slowly) working on getting support for Python 3 in there, but for now, it'll only work in Python 2.

**Comment by teetz** [comment]
Yep that seems to be the problem its working on python 2. thanks!
